### ISSUE TITLE
Rewrite to work with Idris 1.0

### ISSUE THREAD

**Issue by cameron-martin** [davidfstr/idris-insertion-sort#1]
When compiling with idris 0.10, I get the error:

```
InsertionSort.idr:64:18:When checking type of Main.IsSortedZero:
Can't find implementation for Ord e
InsertionSort.idr:77:12:When checking type of Main.mkIsSorted:
When checking argument a to type constructor Prelude.Maybe.Maybe:
        No such variable IsSorted
```

**Comment by davidfstr** [comment]
Acknowledged.

I don't plan on fixing Idris platform incompatibilities until Idris hits at least v1.0 and thereby provides a basic backward-compatibility guarantee. Otherwise I'll just have to keep fixing silly things.
